// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwnfvNRD15Wud-Ah6kbqLHOwdsGx7AQ40',
    appId: '1:937052525568:web:03089dd7d2f4ec93dfb4e5',
    messagingSenderId: '937052525568',
    projectId: 'jobmarketplace-a1007',
    authDomain: 'jobmarketplace-a1007.firebaseapp.com',
    storageBucket: 'jobmarketplace-a1007.appspot.com',
    measurementId: 'G-T59G7Y8NPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqGplMu2uAe6nENUtF83X3qvhNni8rgS8',
    appId: '1:937052525568:android:e1a7d0b5021b1259dfb4e5',
    messagingSenderId: '937052525568',
    projectId: 'jobmarketplace-a1007',
    storageBucket: 'jobmarketplace-a1007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzq5QxWARxcr8u8zVUb9G5JETF1elXunA',
    appId: '1:937052525568:ios:175cbdee207c6ff7dfb4e5',
    messagingSenderId: '937052525568',
    projectId: 'jobmarketplace-a1007',
    storageBucket: 'jobmarketplace-a1007.appspot.com',
    iosClientId: '937052525568-3eank38v0c169mf9hfjln21jdj1co0na.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzq5QxWARxcr8u8zVUb9G5JETF1elXunA',
    appId: '1:937052525568:ios:3fb53c95ff179246dfb4e5',
    messagingSenderId: '937052525568',
    projectId: 'jobmarketplace-a1007',
    storageBucket: 'jobmarketplace-a1007.appspot.com',
    iosClientId: '937052525568-a5bajit77cf4aj5bgrm224pnac5vgofl.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobMarketplace.RunnerTests',
  );
}
